services:
  mariadb:
    extends:
      service: mariadb
      file: ./back/compose.yml

  backend:
    depends_on:
      - mariadb
    extends:
      service: backend
      file: ./back/compose.yml
    env_file:
      - ./back/.env

  frontend:
    depends_on:
      - backend
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4173:4173"

networks:
  external:
      driver: default
      ipam:
          config:
              - subnet: "172.20.0.0/16"
volumes:
  red-tetris-db:
