services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - .env_psql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  red_tetris_db: