services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:4000'

  mariadb:
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env

volumes:
  red_tetris_db:
