services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:4000'

  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  red_tetris_db:
